name: "NibiruChain/run-chaosnet"
description: "Runs a local Chaosnet"

inputs:
  services: # id of input
    description: "Services to start"
    required: false
    default: nibiru oracle
  ghtoken: # id of input
    description: "github secret to pull images"
    required: true
  ghactor: # id of
    description: "github actor"
    required: true

runs:
  using: "docker"
  image: "action/Dockerfile"
  args:
    - ${{ inputs.services }}
    - ${{ inputs.ghtoken }}
    - ${{ inputs.ghactor }}
