name: Tests

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Chaosnet test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run chaosnet
        uses: ./
        id: chaosnet
        with:
          services: nibiru pricefeeder liquidator
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
          ghuactor: ${{ github.actor }}

      - name: Set up Python (3.8)
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.16

      - name: Run python
        run: python --version && python -c "print('hello')"

      - name: Run the examples
        run: |
          pip install nibiru

          python3 -c "import nibiru; print(nibiru.Sdk.authorize().with_network(nibiru.Network.localnet(), True).query.perp.params())"
