name: Test ChaosNet

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.GITHUB_USERNAME }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR container register
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # tag the image with a version when adding a git tag that starts with 'v'
      - name: Build and push versioned image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64

      # - name: Start ChaosNet
      #   uses: docker/build-push-action@v4
      #   with:
      #     compose-file: https://raw.githubusercontent.com/NibiruChain/nibiru/master/contrib/docker-compose/docker-compose-chaosnet.yml
      #     project-name: chaosnet
      #     run: pull

      # Add the following step to keep the workflow running indefinitely
      - name: Keep workflow running
        run: sleep infinity
